/*
 * This source file was generated by the Gradle 'init' task
 */
package assignment;

import java.util.Scanner;

public class App {
    public static int checkInput(int day,int month,int year){
        if(day < 1){
            System.out.println("ระบุวันไม่ถูกต้อง");
            return false;
        }
        if(month < 1 && month > 12){
            System.out.println("ระบุเดือนไม่ถูกต้อง");
            return false;
        }
        if(year < 2500 && year > 2565){
            System.out.println("ระบุปีไม่ถูกต้อง");
            return false;
        }
    }
        public static int Day(int day,int month){
            if(month == 4 || month == 6 || month == 9 || month == 11){
                day = 30;
            }else if (month == 2){
                day = 28;
            }if(day > 31){
                System.out.println("ระบุวันไม่ถูกต้อง");
                return false;
            }
        }
    public static void main(String[] args) {
       Scanner scanIn = new Scanner(System.in);
       while (true) {
        System.out.print("Input day: ");
        int day = scanIn.nextInt();
        System.out.print("Input Month: ");
        int month = scanIn.nextInt();
        System.out.print("Input year: ");
        int year = scanIn.nextInt();

        if(checkInput(day, month, year)){
            System.out.println("Correct!");
            break;
        }else{
            System.out.println("Wrong value!");
        }
       }
    }
}
