/*
 * This source file was generated by the Gradle 'init' task
 */
package assignment02_1;
import java.util.Scanner;
public class App {
    public static long calFactorial(int n) {
        long result = 1;
        for (int i = 1; i <= n; i++) {
            result *= i;
        }
        return result;
    }

    public static long calFibonacci(int n) {
        if (n == 0) return 0;
        if (n == 1) return 1;

        long fib1 = 0, fib2 = 1;
        long fibN = 0;
        for (int i = 2; i <= n; i++) {
            fibN = fib1 + fib2;
            fib1 = fib2;
            fib2 = fibN;
        }
        return fibN;
    }
    public static void main(String[] args) {
        Scanner scanIn = new Scanner(System.in);

        while (true) {
            
            System.out.print("Enter number for calculate: ");
            int number = scanIn.nextInt();

            if (number < 0 || number > 99) {
                System.out.println("Number out of range. Program terminated.");
                break;
            }

            long factorial = calFactorial(number);
            long fibonacci = calFibonacci(number);

            System.out.println("\n" + "Calculation " + number + " Factorial");
            for (int i = 1; i <= number; i++) {
                System.out.println(i + "! = " + calFactorial(i));
            }

            System.out.println("\n" + "Calculation Fibonanci number " + number);
            for (int i = 0; i <= number; i++) {
                System.out.println("f" + i + " = " + calFibonacci(i));
            }

            long result = factorial - fibonacci;
            System.out.println("\n" + number + " Factorial minus Fibonanci number " + number + " is " + result + "\n");
        }
        scanIn.close();
    }

    }

