/*
 * This source file was generated by the Gradle 'init' task
 */
package assignment02_3;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner scanIn = new Scanner(System.in);
        while (true) {
        System.out.print("Input day: ");
        int day = scanIn.nextInt();
        System.out.print("Input Month: ");
        int month = scanIn.nextInt();
        System.out.print("Input year: ");
        int year = scanIn.nextInt();

        if(checkInput(day, month, year)){
            System.out.println("Correct!");
            break;
            }else {
                System.out.println("Wrong value(s)");
            }
        }
        scanIn.close();
         }

    public static boolean checkInput(int day,int month,int year){
        if (year < 2500 || year > 2565) {
            System.out.println("Wrong values");
            return false;
        }

        if (month < 1 || month > 12) {
            System.out.println("Wrong value(s)");
            return false;
        }
        int maxDays = 31;
        if (month == 4 || month == 6 || month == 9 || month == 11) {
            maxDays = 30;
        } else if (month == 2) {
            maxDays = 28;
        }
        if (day < 1 || day > maxDays) {
            System.out.println("Wrong value(s)");
            return false;
        }
        return true;
    }
}
    
    
