/*
 * This source file was generated by the Gradle 'init' task
 */
package assignment02_5;

import java.util.Random;

public class App {

    public static void main(String[] args) {
        int[] a = new int[10];
        Random r = new Random();

        for (int i = 0; i < a.length; i++) {
            a[i] = r.nextInt(60) + 40;
            System.out.println("Score of student " + (i + 1) + " is " + a[i]);
        }
        System.out.println("\nCalculation Grade..");
        for (int i = 0; i < a.length; i++) {
            String grade = Grade(a[i]);
            System.out.println("Grade of student " + (i + 1) + " is " + grade);
        }
    }

    public static String Grade(int score) {
        if (score >= 80) {
            return "A";
        } else if (score >= 75) {
            return "B+";
        } else if (score >= 70) {
            return "B";
        } else if (score >= 65) {
            return "C+";
        } else if (score >= 60) {
            return "C";
        } else if (score >= 55) {
            return "D+";
        } else if (score >= 50) {
            return "D";
        } else {
            return "F";
        }
    }
}
