/*
 * This source file was generated by the Gradle 'init' task
 */
package assignment02_2;
import java.util.Scanner;

public class App {
    public static int mymax(int a, int b, int c) {
        int max = a;
        if (b > max) {
            max = b;
        }
        if (c > max) {
            max = c;
        }
        return max;
    }

    public static int mymin(int a, int b, int c) {
        int min = a;
        if (b < min) {
            min = b;
        }
        if (c < min) {
            min = c;
        }
        return min;
    }

    public static void main(String[] args) {
        Scanner scanIn = new Scanner(System.in);

        System.out.print("Enter first number : ");
        int num1 = scanIn.nextInt();
        System.out.print("Enter second number: ");
        int num2 = scanIn.nextInt();
        System.out.print("Enter last number: ");
        int num3 = scanIn.nextInt();

        int maxValue = mymax(num1, num2, num3);
        int minValue = mymin(num1, num2, num3);

        System.out.println("Max value = " + maxValue);
        System.out.println("Min value = " + minValue);
        System.out.println("Total Max plus Min is " + (maxValue + minValue));

        scanIn.close();
    }
}

